apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "argocd-baitov"
spec:
  destination:
    namespace: projects
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: wordpress
    repoURL: 'https://andreibaitau.github.io/project_wordpress/'
    targetRevision: 1.56.1
