apiVersion: argoproj.io/v1.19.1
kind: Application
metadata:
  name: drupal
  namespace: argocd
spec:
  destination:
    namespace: projects
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: drupal
    repoURL: 'https://andreibaitau.github.io/project_drupal/'
    targetRevision: 1.19.1

