apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drupal
  namespace: argocd
spec:
  destination:
    namespace: projects
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: drupal
    repoURL: 'https://andreibaitau.github.io/project_drupal/'
    targetRevision: 1.0.1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  destination:
    namespace: projects
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: wordpress
    repoURL: 'https://andreibaitau.github.io/project_wordpress/'
    targetRevision: 1.0.1
