apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drupal
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-baitov
spec:
  destination:
    namespace: projects
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: drupal
    repoURL: 'https://andreibaitau.github.io/project_drupal/'
    targetRevision: 1.31.1

